=head1 NAME

gdmflexiserver - start a GDM session using the GDM I<flexible server> mechanism,
or in B<Xnest>

=head1 SYNOPSIS

B<gdmflexiserver>       GNOME options   gdmflexiserver options

=head1 DESCRIPTION

The I<flexi server> mechanism allows to run GDM sessions on demand, in a new
virtual console. The administrator can define multiple server configurations,
using alternate X servers, or different options, in the B<gdm.conf> file, and
B<gdmflexiserver> will present you with a menu, where you will be asked to
choose between those server configurations marked with B<flexible=true>.

Alternatively, the B<--xnest> option allows you to run a new session in an
Xnest(1) window.

=head1 OPTIONS

In addition to the common Gtk and GNOME options, B<gdmflexiserver> accepts the
following options:

=over 4

=item B<-c> I<command>, B<--command>=I<command>

Send the specified protocol command to gdm

=item B<-n>, B<--xnest>

Xnest mode

=item B<-l>, B<--no-lock>

Do not lock current screen

=item B<-d>, B<--debug>

Debugging output

=item B<-a>, B<--authenticate>

Authenticate before running B<--command>

=back

=head1 SEE ALSO

gdm(8), Xnest(1).

=head1 AUTHORS

B<gdmflexiserver> is part of the B<GDM> software package, which is part of the
GNOME project. This manpage was written by Yann Dirson <dirson@debian.org> for
the Debian system, but may be used by others.
