=head1 NAME

mdmchooser - MDM Display Manager host chooser window

=head1 SYNOPSIS

mdmchooser

=head1 DESCRIPTION

B<mdmchooser> is invoked by mdm(8). It displays a list of hosts that
are candidates for logging into via a mdm(8) daemon or compatible,
such as xdm(1x) or wdm(1x).

=head1 SEE ALSO

mdm(8)

=head1 AUTHOR

Martin Kasper Petersen <mkp@SunSITE.auc.dk>

This manual page written by Steve Haslam <araqnid@debian.org> for
Debian GNU/Linux.

=cut
