=head1 NAME

mdmflexiserver - start a MDM session using the MDM I<flexible server> mechanism

=head1 SYNOPSIS

B<mdmflexiserver>       GNOME options   mdmflexiserver options

=head1 DESCRIPTION

The I<flexi server> mechanism allows to run MDM sessions on demand.

=head1 OPTIONS

In addition to the common Gtk and GNOME options, B<mdmflexiserver> accepts the
following options:

=over 4

=item B<-c> I<command>, B<--command>=I<command>

Send the specified protocol command to mdm

=item B<-l>, B<--no-lock>

Do not lock current screen

=item B<-d>, B<--debug>

Debugging output

=item B<-a>, B<--authenticate>

Authenticate before running B<--command>

=back

=head1 SEE ALSO

mdm(8)

=head1 AUTHORS

B<mdmflexiserver> is part of the B<MDM> software package. This manpage was written by Yann Dirson <dirson@debian.org> for
the Debian system, but may be used by others.
