=head1 NAME

mdmlogin - MDM Display Manager greeting window

=head1 SYNOPSIS

mdmlogin

=head1 DESCRIPTION

B<mdmlogin> is invoked by mdm(8). It displays a GNOME login window
and obtains a login/password combination from the user. This is then
sent to the controlling B<mdm> process for verification.

=head1 SEE ALSO

mdm(8)

=head1 AUTHOR

Martin Kasper Petersen <mkp@SunSITE.auc.dk>

This manual page written by Steve Haslam <araqnid@debian.org> for
Debian GNU/Linux. Updated by Raphaël Hertzog <hertzog@debian.org>.
Updated by Ryan Murray <rmurray@debian.org>.

=cut
